# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'

target 'Popping' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Popping
  pod "pop"
  pod "AFNetworking"
  target 'PoppingTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
