# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'Swift3' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swift3
  pod 'LeanCloud', :git => 'git@github.com:leancloud/swift-sdk.git', :tag => '0.0.1.beta'
end
