# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'weddingTime' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for weddingTime
  pod 'AVOSCloud'   , '3.3.3'
  pod 'AVOSCloudIM' , '3.3.3'
  pod 'SDWebImage'  , '3.7.2'
  pod 'AFNetworking', '3.1.0'
  pod "Qiniu", :git => 'https://github.com/qiniu/objc-sdk.git', :branch => 'AFNetworking-3.x'
  pod 'FMDB'
  pod 'Masonry'
  pod 'MBProgressHUD'
  pod 'pop'
  pod 'BaiduMapKit'
  pod 'UMengAnalytics', '3.5.8'
  pod 'M13ProgressSuite', '1.2.7'
  pod 'WeiboSDK'
  pod 'TencentOpenApiSDK'
  pod 'libWeChatSDK'

  #  pod 'NMRangeSlider', '1.2.1'
  #	 pod 'Base64nl', '1.2'
  #  pod 'AsyncDisplayKit'

  target 'weddingTimeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
