CREATE TABLE CONTACTS                                
(USERID INTEGER,
USER_NAME     VARCHAR(100),
NICK_NAME     VARCHAR(100),
SEX           INTEGER,
LOGO          VARCHAR(500),
PRIMARY KEY (USERID));

CREATE TABLE FRIENDS
(USERID INTEGER,
USER_NAME     VARCHAR(100),
NICK_NAME     VARCHAR(100),
SEX           INTEGER,
LOGO          VARCHAR(500),
COUNTRY       VARCHAR(100),
CITY          VARCHAR(100),
PRIMARY KEY (USERID));