# Uncomment this line to define a global platform for your project
platform :ios, ‘7.0’
# Uncomment this line if you're using Swift
# use_frameworks!

target 'ChatDemo' do
pod 'AVOSCloud'
pod 'AVOSCloudIM'
pod 'FMDB'
pod "AFNetworking", '3.0.0'
end

